package de.moges.test.jenkins.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SpecialityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialityAllPropertiesEquals(Speciality expected, Speciality actual) {
        assertSpecialityAutoGeneratedPropertiesEquals(expected, actual);
        assertSpecialityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialityAllUpdatablePropertiesEquals(Speciality expected, Speciality actual) {
        assertSpecialityUpdatableFieldsEquals(expected, actual);
        assertSpecialityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialityAutoGeneratedPropertiesEquals(Speciality expected, Speciality actual) {
        assertThat(expected)
            .as("Verify Speciality auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialityUpdatableFieldsEquals(Speciality expected, Speciality actual) {
        assertThat(expected)
            .as("Verify Speciality relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialityUpdatableRelationshipsEquals(Speciality expected, Speciality actual) {
        // empty method
    }
}
